import React, { useMemo } from 'react';
import { TestSeriesBundle } from '../data/bundleCatalog';
import { MockTest } from '../types';
import { BundleDetailPage } from './BundleDetailPage';
import { ArrowRight, BookOpen, BriefcaseBusiness, CheckCircle2, ChevronRight, GraduationCap, Users } from 'lucide-react';

interface CGSSBRecruitmentHubProps { bundles: TestSeriesBundle[]; tests: MockTest[]; onStartTest: (test: MockTest) => void; onExplorePass: () => void; }
type Track = { key:string; slug:string; name:string; hindi:string; vacancies:number; description:string; subjects:string[]; keywords:string[]; };
const TRACKS: Track[] = [
 { key:'assistant-teacher', slug:'assistant-teacher', name:'Assistant Teacher', hindi:'सहायक शिक्षक', vacancies:2292, description:'Primary cadre preparation with full-length mocks, subject tests and previous-year papers.', subjects:[], keywords:['assistant teacher','sahayak shikshak','primary'] },
 { key:'teacher', slug:'teacher', name:'Teacher / TGT', hindi:'शिक्षक / टीजीटी', vacancies:1654, description:'Subject-wise preparation for the middle-school teacher recruitment examination.', subjects:['English','Hindi','Mathematics','Science','Social Science'], keywords:['subject teacher','teacher','tgt','middle school'] },
 { key:'lecturer', slug:'lecturer', name:'Lecturer / PGT', hindi:'व्याख्याता / पीजीटी', vacancies:854, description:'Postgraduate-level subject preparation with focused test series and mocks.', subjects:['English','Hindi','Mathematics','Physics','Chemistry','Biology'], keywords:['lecturer','vyakhyata','pgt'] },
];
const normalize = (value:string) => value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function matchesTrack(bundle:TestSeriesBundle, track:Track) { const text=normalize(bundle.targetPost || bundle.title); return track.keywords.some(k=>text.includes(normalize(k))); }
function matchesSubject(bundle:TestSeriesBundle, subject:string) { return normalize(bundle.targetPost || bundle.title).includes(normalize(subject)); }

export const CGSSBRecruitmentHub:React.FC<CGSSBRecruitmentHubProps> = ({bundles,tests,onStartTest,onExplorePass}) => {
 const path=typeof window!=='undefined'?window.location.pathname.toLowerCase():'/cgssb/teacher-recruitment-2026';
 const parts=path.split('/').filter(Boolean); const trackSlug=parts[2]||''; const subjectSlug=parts[3]||'';
 const visibleBundles=useMemo(()=>bundles.filter(b=>b.authority==='CGSSB' && b.isPublished!==false && !b.isDraft),[bundles]);
 const selectedTrack=TRACKS.find(t=>t.slug===trackSlug);
 const navigate=(target:string)=>{ window.history.pushState({},'',target); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({top:0,behavior:'smooth'}); };
 const findSubjectBundle=(track:Track,subject:string)=>visibleBundles.find(b=>matchesTrack(b,track)&&matchesSubject(b,subject));

 if(selectedTrack && subjectSlug){
   const subject=selectedTrack.subjects.find(s=>normalize(s).replace(/ /g,'-')===subjectSlug);
   const subjectBundle=subject?findSubjectBundle(selectedTrack,subject):undefined;
   if(subjectBundle) return <BundleDetailPage bundle={subjectBundle} availableTests={tests} onBack={()=>navigate('/cgssb/teacher-recruitment-2026')} onStartTest={onStartTest} onExplorePass={onExplorePass} isEnrolled={false} onEnrollSuccess={()=>undefined}/>;
   return <div className='rounded-3xl border border-slate-800 bg-slate-900/80 p-8 text-center space-y-3'><p className='text-sm font-black text-white'>{subject || 'Subject'} preparation</p><p className='text-xs text-slate-400'>The subject-wise test series is being prepared. Please choose another available subject.</p><button onClick={()=>navigate('/cgssb/teacher-recruitment-2026')} className='inline-flex items-center rounded-xl bg-emerald-500 px-4 py-2 text-xs font-black text-slate-950'>Back to Recruitment</button></div>;
 }
 if(selectedTrack){
   const trackBundles=visibleBundles.filter(b=>matchesTrack(b,selectedTrack)); const primaryBundle=trackBundles[0];
   return <div className='space-y-6'><button onClick={()=>navigate('/cgssb/teacher-recruitment-2026')} className='text-xs font-bold text-slate-400 hover:text-white'>← Back to Teacher Recruitment</button>
    <section className='rounded-3xl border border-emerald-900/40 bg-gradient-to-br from-emerald-950/60 via-slate-900 to-slate-950 p-6 sm:p-8'><div className='flex flex-col sm:flex-row sm:items-start sm:justify-between gap-5'><div><p className='text-[11px] font-black uppercase tracking-widest text-emerald-400'>CGSSB Teacher Recruitment 2026</p><h2 className='mt-2 text-2xl sm:text-3xl font-black text-white'>{selectedTrack.name}</h2><p className='mt-1 text-sm text-slate-400'>{selectedTrack.hindi} · {selectedTrack.vacancies.toLocaleString('en-IN')} vacancies</p></div></div>
    {selectedTrack.subjects.length>0 ? <div className='mt-7'><p className='text-xs font-black uppercase tracking-wider text-slate-300 mb-3'>Choose your subject</p><div className='grid grid-cols-2 sm:grid-cols-3 gap-3'>{selectedTrack.subjects.map(subject=>{ const hasSeries=Boolean(findSubjectBundle(selectedTrack,subject)); const slug=normalize(subject).replace(/ /g,'-'); return <button key={subject} onClick={()=>navigate('/cgssb/teacher-recruitment-2026/'+selectedTrack.slug+'/'+slug)} className='group rounded-2xl border border-slate-800 bg-slate-950/70 p-4 text-left hover:border-emerald-500/50 transition'><div className='flex items-center justify-between'><BookOpen className='h-4 w-4 text-emerald-400'/><ChevronRight className='h-4 w-4 text-slate-600 group-hover:text-emerald-400'/></div><p className='mt-3 text-sm font-black text-white'>{subject}</p><p className='mt-1 text-[10px] font-bold text-slate-500'>{hasSeries?'Test series available':'Coming soon'}</p></button>; })}</div></div> : <div className='mt-7 rounded-2xl border border-slate-800 bg-slate-950/60 p-5'><p className='text-sm font-black text-white'>Complete preparation suite</p><p className='mt-1 text-xs text-slate-400'>Full mocks, subject tests and previous-year papers in one preparation track.</p>{primaryBundle&&<button onClick={()=>navigate('/cgssb/teacher-recruitment-2026/'+selectedTrack.slug+'/series')} className='mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2.5 text-xs font-black text-slate-950'>Start Preparing <ArrowRight className='h-4 w-4'/></button>}</div>}
    </section></div>;
 }
 return <div className='space-y-6'><section className='relative overflow-hidden rounded-3xl border border-emerald-900/40 bg-gradient-to-br from-emerald-950/70 via-slate-900 to-slate-950 p-6 sm:p-10'><div className='relative z-10 max-w-4xl'><div className='inline-flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-[11px] font-black text-emerald-300'><BriefcaseBusiness className='h-3.5 w-3.5'/>CGSSB Teacher Recruitment 2026</div><h1 className='mt-4 text-3xl sm:text-5xl font-black tracking-tight text-white'>Prepare for the post you want.</h1><p className='mt-3 max-w-2xl text-sm sm:text-base leading-relaxed text-slate-300'>One recruitment, three career tracks. Choose your post and go directly to the preparation you need.</p><div className='mt-6 flex flex-wrap items-center gap-3 text-xs'><span className='inline-flex items-center gap-2 rounded-xl border border-emerald-500/20 bg-slate-950/70 px-3 py-2 font-black text-white'><Users className='h-4 w-4 text-emerald-400'/>4,800 Vacancies</span><span className='rounded-xl border border-slate-800 bg-slate-950/60 px-3 py-2 text-slate-300'>3 Posts</span><span className='rounded-xl border border-slate-800 bg-slate-950/60 px-3 py-2 text-slate-300'>Assistant Teacher · Teacher · Lecturer</span></div></div></section>
 <div className='grid grid-cols-1 lg:grid-cols-3 gap-4'>{TRACKS.map(track=>{ const trackBundles=visibleBundles.filter(b=>matchesTrack(b,track)); return <article key={track.key} className='rounded-3xl border border-slate-800 bg-slate-900/80 p-5 sm:p-6 flex flex-col'><div className='flex items-start justify-between gap-3'><div className='h-11 w-11 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center'><GraduationCap className='h-5 w-5 text-emerald-400'/></div><span className='text-xs font-black text-emerald-300'>{track.vacancies.toLocaleString('en-IN')} vacancies</span></div><h2 className='mt-5 text-xl font-black text-white'>{track.name}</h2><p className='mt-1 text-xs font-semibold text-slate-500'>{track.hindi}</p><p className='mt-4 text-sm leading-relaxed text-slate-400'>{track.description}</p>{track.subjects.length>0&&<div className='mt-5 flex flex-wrap gap-1.5'>{track.subjects.map(s=><span key={s} className='rounded-lg border border-slate-800 bg-slate-950/70 px-2 py-1 text-[10px] font-bold text-slate-300'>{s}</span>)}</div>}<div className='mt-5 flex items-center gap-2 text-[11px] font-bold text-slate-500'><CheckCircle2 className='h-3.5 w-3.5 text-emerald-400'/>{trackBundles.length>0?trackBundles.length+' preparation series available':'Preparation series being added'}</div><button onClick={()=>navigate('/cgssb/teacher-recruitment-2026/'+track.slug)} className='mt-6 w-full inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-500 px-4 py-3 text-xs font-black text-slate-950 hover:bg-emerald-400 transition'>{track.subjects.length>0?'Explore Tests':'Start Preparing'}<ArrowRight className='h-4 w-4'/></button></article>; })}</div>
 <div className='rounded-2xl border border-slate-800 bg-slate-950/50 p-4 text-xs text-slate-500'>Vacancy figures shown here are recruitment metadata. Always verify notification, eligibility, dates and reservation details against the latest CGSSB notice.</div></div>;
};